### ISSUE TITLE
Youtube support

### ISSUE THREAD

**Issue by vitalets** [SamsungDForum/SmartViewSDKDefaultMediaPlayer2.0#1]
Hi

Does DMP support playing youtube videos?
I see they are commented in code:
https://github.com/SamsungDForum/SmartViewSDKDefaultMediaPlayer2.0/blob/527ab13e08f277b035ffecbb7608834700a6f5c5/DMP_Adroid/DefaultMediaPlayer2.0/app/src/main/assets/videolist.json#L57

**Comment by monster-mj** [comment]
Hi,
Yes, DMP support youTube contents.
You should keep content url
**http://www.youtube.com/embed/ + videoID**
ex) "url": "http://www.youtube.com/embed/fwkJtgVswgM"

**Comment by vitalets** [comment]
Thank you! 
Also will this work with other video hostings or only youtube is possible?

**Comment by monster-mj** [comment]
Hi, Both
Refer to DMP v1.0
**Youtube URL :** 
ex) "url": "http://www.youtube.com/embed/fwkJtgVswgM"
https://github.com/SamsungDForum/SmartViewSDKDefaultMediaPlayer/blob/master/DMP_Adroid/DefaultMediaPlayer/app/src/main/java/samsung/defaultmediaplayer/YouTubeFragment.java#L146

**Conents Server URL :** 
ex) "url": "http://www.samsungdforum.com/smartview/sample/video/BigBuckBunny.mp4"
https://github.com/SamsungDForum/SmartViewSDKDefaultMediaPlayer/blob/master/DMP_Adroid/DefaultMediaPlayer/app/src/main/java/samsung/defaultmediaplayer/VideosFragment.java#L114

In DMP v2.0, create VideoPlayer then add URL that you  want to play.

refer to other DMP v2.0 guide
https://www.samsungdforum.com/TizenGuide/tizen4941/index.html

**Comment by vitalets** [comment]
Hi @monster-mj 

thanks for answer! All your examples worked.
But I am developing mobile app that should stream video from different video providers.
I tried DMP with 2 non-youtube providers and it does not work.
Example urls:
1. https://ok.ru/videoembed/203221633706?autoplay=1
2. https://vk.com/video_ext.php?oid=-72965975&id=171625926&hash=7b90d8ea05d9cab2&autoplay=1

I just got black screen. 
Is it possible to play it with DMP?

**Comment by monster-mj** [comment]
Hi @vitalets 
DMP2.0 supports only general media spec and adative streaming(mpeg-dash/hls/smooth streaming)
https://www.samsungdforum.com/Tizen/Spec#2016TVSpec
https://www.samsungdforum.com/Tizen/Spec#2015TVSpec

especailly, DMP supports youtube video content.
but, other provider's content  that you mentioned can't play

**Comment by monster-mj** [comment]
I closed this issue
