### ISSUE TITLE
Unable to cast content, lack of error information

### ISSUE THREAD

**Issue by tomas-paronai** [SamsungDForum/SmartViewSDKDefaultMediaPlayer2.0#3]
I have pulled and installed this sample app on my samsung galaxy note 4. I did found the tv in connections and was able to connect to it (cast icon turned blue). 
When I choose a media from all 3 categories, I always get a Toast message saying "Error in Launching content". 
When I check the log output in IDE, it says "playContent(): onError: Not Found".

**Log since connecting to TV and choosing a content to play:**

> > 01-10 13:58:02.073 9703-9703/samsung.mediaplayerqueue D/CastStateM.Singleton: Cast Satatus Changed to: CONNECTED
> 01-10 13:58:02.083 9703-9703/samsung.mediaplayerqueue V/TVSearch: Stopping Discovery.
> 01-10 13:58:02.113 9703-9703/samsung.mediaplayerqueue E/ViewRootImpl: sendUserActionEvent() mView == null
> 01-10 13:58:07.103 9703-9703/samsung.mediaplayerqueue V/TVSearch: Discovery Stopped.
> 01-10 13:58:10.323 9703-9703/samsung.mediaplayerqueue D/ViewRootImpl: ViewPostImeInputStage processPointer 0
> 01-10 13:58:10.383 9703-9703/samsung.mediaplayerqueue D/ViewRootImpl: ViewPostImeInputStage processPointer 1
> 01-10 13:58:10.453 9703-9703/samsung.mediaplayerqueue V/MediaLauncherSingleton: Playing Content: http://developer.samsung.com/onlinedocs/tv/SmartView/sample/video/BigBuckBunny.mp4
> 01-10 13:58:10.453 9703-9703/samsung.mediaplayerqueue D/MediaPlayer: Player Connection Status : false
> 01-10 13:58:10.453 9703-9703/samsung.mediaplayerqueue D/MediaPlayer: Is Connected Status : false
> 01-10 13:58:10.673 9703-9703/samsung.mediaplayerqueue D/MediaPlayer: Content Url : http://developer.samsung.com/onlinedocs/tv/SmartView/sample/video/BigBuckBunny.mp4
> 01-10 13:58:10.983 9703-9703/samsung.mediaplayerqueue D/MediaPlayer: StartPlay() Error: Error(code=404, name=error, message=Not Found)
> 01-10 13:58:10.983 9703-9703/samsung.mediaplayerqueue V/MediaLauncherSingleton: playContent(): onError: Not Found

**Comment by monster-mj** [comment]
@tomas-paronai 
Hi, tomas
first of all, I want to know your TV infomation.
plz, give me your TV model ad S/W version
TV-Menu-Contact Samsung - **_Model name & S/W version_**

**Comment by tomas-paronai** [comment]
![pasted image at 2017_01_09 03_19 pm](https://cloud.githubusercontent.com/assets/15670545/21798270/c62a4e66-d713-11e6-8e05-1de100306e05.png)

**Comment by monster-mj** [comment]
thanks,
ok, I confirmed your TV support SmartViewSDK&DMP feature,

Let's check 
1. Can U use CURL?  we need to get TV app info though GET Method
   curl -v "_**http://YOUR_TV_IP:8001**_/api/v2/applications/**_3201412000694_**"

or

2. install REST Request android app(like HTTP Requester)
   input URL : "_**http://YOUR_TV_IP:8001**_/api/v2/applications/**_3201412000694_**"
   and push GET button

3201412000694 is web app to play media in TV(AKA. Defaul Media Player)
If it is nomal, GET method return
{
  "name": "App Launcher",
  "running": false,
  "version": "3.1.18",
  "visible": false,
  "id": "3201412000694",
  "media_player": false,
  "appName": ""
}

but, if it has some problem GET method return
{
  "status": 404,
  "message": "Not Found",
  "code": 404
}

plz, let me know your 3201412000694 status.

NOTE : 
SmartView app is not releated with SmartViewSDK. only the name is similar.
SmartView app use DLNA to show photo and play music.....

**Comment by tomas-paronai** [comment]
It have returned 404.

**Comment by tomas-paronai** [comment]
I have found the problem. TV was not connected to the internet.... I got confused, we have an android box connected to the TV which is connected to the internet. The TV itself was not connected. I had to submit some security permission to allow TV access the internet. 
Everything works as it should. Thank you for your time.

**Comment by Liviu-D** [comment]
Hi monster
I have the same problem like tomas. I tried everything you described above on the page. But nothing went work.
My tv model is UE32F5300 and software version is T-MST12DEUC-2126.0
Thanks

**Comment by ankitsaini3005** [comment]
Hello Liviu,
Can you please tell me ~ what's the status of last step ?

3.install REST Request android app(like HTTP Requester)
 input URL : "http://YOUR_TV_IP:8001/api/v2/applications/3201412000694"
 and push GET button

3201412000694 is web app to play media in TV(AKA. Defaul Media Player)
 If it is nomal, GET method return
 {
 "name": "App Launcher",
 "running": false,
 "version": "3.1.18",
 "visible": false,
 "id": "3201412000694",
 "media_player": false,
 "appName": ""
 }

but, if it has some problem GET method return
 {
 "status": 404,
 "message": "Not Found",
 "code": 404
 }

plz, let me know your 3201412000694 status.
