### ISSUE TITLE
Is the code updated? Build error.

### ISSUE THREAD

**Issue by JackTedo** [SamsungDForum/SmartViewSDKDefaultMediaPlayer2.0#4]
I downloaded and built the iOS code with error: "(import smartview) module compiled with swift 3.0 cannot be imported in swift 3.1". So I downloaded the latested SmartView.framework (Mar 30, 2017 14MB 2.4.2) and replaced the one in the code but got more build errors. Can this code be updated to remove this errors?

It seems that Smartview support a limited [Samsung smart TV](http://developer.samsung.com/tv/develop/extension-libraries/smart-view-sdk/supported-device/supported-tvs), is it true? If I want to develop iOS app( similiar to remote controller for TV), what is the best practice to support  as more as possible samsung TVs?

**Comment by monster-mj** [comment]
@JackTedo ,
Sorry too late response.
we missed some DMP code with 2.4.2 framework. It will be updated soon.

Yes, There is separatly the supporting model.
Each TV has own features and SmartViewSDK is supported a little bit high sepcification.

**Comment by JackTedo** [comment]
Great and thanks very much.
