### ISSUE TITLE
Connection lost when screen off iOS

### ISSUE THREAD

**Issue by TrungNguyen1208** [SamsungDForum/SmartViewSDKDefaultMediaPlayer2.0#6]
Hi, I'm using this lib in my objective-C project. When I turn off screen and turn on it again, my app crash with the following error:
onDisconnect ---- Error is Optional(Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={_kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1})
The swift sample lost connection too but it does not crash.
Please help me to fix it

**Comment by qttoan-khtn** [comment]
Hi @TrungNguyen1208 ,
Just add `photoplayer?.connectionDelegate = self`, this issue will resolve
Thanks
